makenotion/notion-sdk-js

.eslintrc.js
.github/workflows/ci.yml
.prettierrc
.vscode/settings.json
README.md
ava.config.js
examples/database-update-send-email/README.md
examples/database-update-send-email/index.js
examples/github-issue-sync/README.md
examples/github-issue-sync/index.js
package.json
src/Client.ts
src/api-endpoints.ts
src/api-types.ts
src/errors.ts
src/helpers.ts
src/index.ts
src/logging.ts
test/client-basics.ts
tsconfig.json

Add prettier and apply to the codebase. This should keep the codebase looking nice.

Apply prettier

---

.github/ISSUE_TEMPLATE/bug_report.md
.prettierignore

This pull request fixes the CI build failures in a better way. Refer to #101 conversation for the context.

Fix #101 in a better way

---

examples/database-email-update/index.js

fix email glitch example

---

src/api-endpoints.ts

Add missing archived parameter, so pages can be deleted.
Fixes #68

Add archived parameter

---

examples/database-email-update/index.js
examples/database-email-update/package.json
examples/notion-github-sync/index.js
examples/notion-github-sync/package.json

Was not really up to normal Notion code quality, did not use the notion client as one would expect, and there were some issues with the existing script.
Closes https://github.com/makenotion/notion-sdk-js/issues/14
Closes https://github.com/makenotion/notion-sdk-js/pull/120

[examples] test and improve glitch examples

---

examples/database-email-update/package.json
examples/notion-github-sync/package.json
package.json
src/api-endpoints.ts
src/api-types.ts

Support Media Block Types

---

src/api-types.ts

Quick PR to add missing RelationPropertyValue type definition

feat: add RelationPropertyValue

---

examples/database-email-update/package.json
examples/notion-github-sync/package.json
package.json

Follow-up to https://github.com/makenotion/notion-sdk-js/pull/204

Bump to version 0.4.1

---

src/api-endpoints.ts

This PR updates api-endpoints.ts following the instructions here: https://dev.notion.so/notion/Update-Notion-JS-SDK-57cce3061ed04a33b4663fee8f6f9ad1

[api] notion build-public-api-js-sdk

---

package.json

Following the instructions here: https://dev.notion.so/notion/Update-Notion-JS-SDK-57cce3061ed04a33b4663fee8f6f9ad1#9315fa24f454468db5be4a3d8d8e5934

Version bump to 0.4.12

---

src/Client.ts

fix: Using right notion API version

---

examples/database-email-update/index.js
examples/database-email-update/package.json
examples/notion-github-sync/index.js
examples/notion-github-sync/package.json

Also updated and tested corresponding glitch examples:
https://glitch.com/edit/#!/notion-database-email-update
https://glitch.com/edit/#!/notion-github-sync

update glitch examples to use property item endpoint

---

src/Client.ts
src/api-endpoints.ts

- Update auto-generated types
- Update client to use new Notion-Version
Will file a separate PR with the NPM package version bump.

Update client for version 2022-06-28

---

examples/notion-github-sync/README.md

Fixes issue #305. Outdated path.

Fix issue in example readme.

---

README.md
src/Client.ts
src/api-endpoints.ts
src/helpers.ts
src/index.ts

Adds `Client.comments.list` and `Client.comments.create`.

Support for comments API

---

package.json

Includes small fix to `search` so it works with pagination utilities.
Updates package.json with patch version update.

Version 2.1.1

---

src/api-endpoints.ts

This PR includes:
- workspace_name change
- `ButtonPropertyItemObjectResponse` from simon
- `comment_id` change from maybe clara

feat(workspaceName): add workspace_name to bot object

---

package.json
src/api-endpoints.ts
src/utils.ts

closes https://github.com/makenotion/notion-sdk-js/issues/345
Call me dependabot cuz I be depending.
~Updated all dependencies while I was at it, why not?~ Oh right because it's a nightmare.

update typescript and eslint package dependencies

---

src/api-endpoints.ts

Add Singapore Dollar to DB number format

---

src/api-endpoints.ts

Add support for creating template mentions. Also some minor changes to support filtering by status property in `queryDatabase`, and some emoji changes.

Add support for creating template mentions

---

package.json

Add support for creating template mentions in #396

Version Bump: 2.2.4

---

src/api-endpoints.ts

We now support `peruvian_sol`, so updating the SDK. The [API docs](https://developers.notion.com/reference/property-object#number) have been updated as well.

Add peruvian_sol

---

package.json

Includes following changes:
- Fix bug for in `filter_properties` query parameter to correctly URI encode property IDs when passed via the JS SDK
- Add `peruvian_sol` to acceptable `NumberFormat` options

Upgrade to 2.2.5

---

src/api-endpoints.ts

Add support for:
- Unique ID for pages
- Public URL (if available)
- Appending after a block

[Update SDK] Add support for unique ID, public URL, and appending after a block

---

package.json

Add support for:
- Unique ID for pages
- Public URL (if available)
- Appending after a block

Version Bump: 2.2.6

---

package.json

* Removes a reference to DOM lib types

Bump version to 2.2.8

---

package.json

Export missing helper `isFullPageOrDatabase`

Version bump (2.2.10)

---

src/api-endpoints.ts

Fixes https://github.com/makenotion/notion-sdk-js/issues/427.

Update rollup types for `show_original` calculation

---

package.json

Includes changes from:
- #438
- #439

Version bump (2.2.11) 

---

package.json

Includes database endpoint update to support unique ID properties and language for notion formulas.

Bump version to v2.2.12

---

src/api-endpoints.ts

Ran `build-public-api-js-sdk` to pick up the newest API changes

Update SDK with file block name, toggle table children, more emoji, more timezones

---

.github/workflows/semgrep.yml

This PR adds Semgrep codescanning as a CI test per @rhart92's request.

Add Semgrep security code scanning

---

package.json

Following [guide](https://dev.notion.so/notion/Update-Notion-JS-SDK-57cce3061ed04a33b4663fee8f6f9ad1?pvs=4#9315fa24f454468db5be4a3d8d8e5934)
ran `npm version patch`

bump patch version to 2.2.15

---

package.json

Ran `npm version patch`
This new version tag will include the changes from https://github.com/makenotion/notion-sdk-js/pull/545

Bump patch version to 2.2.16

---

package.json

Ran `npm version patch`
This new version tag will include the changes from https://github.com/makenotion/notion-sdk-js/pull/550

Bump patch version to 2.2.17

---

package.json

Ran `npm version minor`
This new version tag will include the changes from #552

Bump minor version to 2.3.0

---

package.json

Commits the result of `npm run patch`
Includes this PR: https://github.com/makenotion/notion-sdk-js/pull/568

Patch version bump: v3.1.0 → v3.1.1

---

package.json

Commits the result of `npm run patch`
Includes this PR: https://github.com/makenotion/notion-sdk-js/pull/570

Patch version bump: v3.1.1 → v3.1.2

---

package.json

Commits the result of `npm run patch`
Includes these PRs:
- https://github.com/makenotion/notion-sdk-js/pull/573
- https://github.com/makenotion/notion-sdk-js/pull/574

Patch version bump: v3.1.2 → v3.1.3

---

src/api-endpoints.ts

Added detailed JSDoc comments and removed redundant null types.

chore: add JSDoc comments to API types

---

src/api-endpoints.ts

Added support for comment attachments in the Comment API endpoints.

Add support for attachments in Comment API

---

.cspell.json
.github/copilot-instructions.md

This PR commits the result of a `.github/copilot-instructions.md` file generated with the help of Cursor agent. This can help improve the quality Copilot code reviews and flag certain files that are generated and should not be commented on, e.g. `src/api-endpoints.ts`
General context: https://docs.github.com/en/copilot/how-tos/configure-custom-instructions/add-repository-instructions#creating-repository-wide-custom-instructions-1
N/A; we can manually test this by seeing how Copilot code reviewer behaves.
N/A

Add Copilot instructions file for repo
