- examples/database-update-send-email/README.md
- examples/github-issue-sync/README.md
This PR fixes the broken readme banner images. The rest of the `notion.com` links get redirected to `notion.so` but `dev.notion.com` doesn't so these image urls still need the `.so` tld.
> fix: update image links

- .prettierignore
- package.json
This pull request fixes the build failure with the latest revision. The command `npm i` fails as it tries to validate the markdown files under `.github` directory.
> Fix CI build failures

- src/api-types.ts
I found `MultiSelectProperty` interface is declared twice, so I deleted one.
> Remove duplicating type

- .prettierignore
- src/api-types.ts
Block children are currently of type BlockBase[]. In my use case I am unable to fetch the children of a particular block and add them to this property because of its type.
Also added .github to prettierignore since it was breaking the checks.
> Changes Block children prop type to Block[]

- .eslintrc.js
- .github/workflows/ci.yml
- README.md
- package.json
- src/Client.ts
- src/errors.ts
- src/fetch-types.ts
- src/helpers.ts
- src/index.ts
- src/type-utils.ts
- tsconfig.json
- Rework error types. This is a breaking change.
- replace `got` with `node-fetch`, similar to whatwg-fetch.
- Allow pluggable `fetch` function that supports the subset of fetch options compatible with `node-fetch` & browser fetch
- use package.json version in user-agent header
- Partially addresses #60, although does not provide a solution for security or CORS.
- Because we no longer import big expensive dependencies, consumers will be able to subclass `Client` to override the `request` method to implement proxying requests via the server.
- This adds some new code, but also removes some got-specific code of about the same length. The trade-off seems worth it.
- I haven't tested this code yet, and unfortunately we don't have any tests for `Client.prototype.request`. Being able to inject …
> Rework error types, remove got in favor of node-fetch

- README.md
There's a missing `await` in the TypeScript example
> missing `await` in TypeScript example

- src/api-types.ts
fix #131 
Change id and color of interface SelectOption to be optional in src/api-types.ts.
```
export interface SelectOption {
name: string
id?: string
color?: Color
}
```
This PR may be also related to #129.
> Let id and color optional in SelectOption

- src/api-types.ts
Returns from the API show that the type of a file property should be `files`, not `file`.
Also, this PR makes a name change to `FileProperty` so that it follows the naming convention.
It fixes #107.
> Correct type from `file` to `files` in the typing file

- src/api-types.ts
Changes `api-types.ts` to require one of `name` or `id` in `SelectOption` and make `color` optional.
Fixes #129 and #131.
> Require one of name or id in SelectOption, make color optional

- .github/workflows/ci.yml
Given that nodejs v16 is the latest LTS, I think we could include it in CI tests.
https://nodejs.org/en/about/releases/
> chore(ci): nodejs v16

- src/api-types.ts
Updating for [this fix](https://developers.notion.com/changelog/rollup-property-functions-now-include-show_original)
> Add show_original to rollup property types

- src/api-types.ts
Adding name to property schema object for this [update](https://developers.notion.com/changelog/database-property-objects-now-include-property-name).
> Add name to property schema object

- src/Client.ts
- src/api-endpoints.ts
- src/api-types.ts
- src/helpers.ts
Adds support for
* PATCH /blocks/:id endpoint
* GET /blocks/:id endpoint
* update helper function to support Union types
> Add update and retrieve block endpoints to sdk

- src/Client.ts
- src/api-endpoints.ts
- src/api-types.ts
Adding support for update database: https://developers.notion.com/reference/update-a-database
> Add update database to client

- src/api-types.ts
Make corresponding types nullable, now that we return `null` for empty page properties.
> Make property values nullable

- src/api-types.ts
The response shape of a date formula returns as follows:
```json
"page": {
"properties": {
"Published Date": {
"formula": {
"date": {
"start": ...
}
}
}
}
}
```
The current type for a date based formula, however, expects that there be a nested date field (i.e. `formula.date.date.start`). Thus, when using TypeScript, accessing the true path to the `start` field will produce a TS error:
```
Property 'start' does not exist on type 'DatePropertyValue'.ts(2339)
```
> feat: correct typing for DateFormulaValue date field

- src/api-endpoints.ts
Should return `Page` not `BlockBase`
> Fix pages.create() response type

- src/api-types.ts
Bookmark Blocks were documented on this [API Reference](https://developers.notion.com/reference/block#bookmark-blocks) page, but there are no type definitions of it.
> Add missing bookmark block types

- .cspell.json
- package.json
- scripts/verifyLoggedIn.sh
**Description:** Currently when we publish a new version, if you aren't logged into NPM you don't see an error until after all the checks. This PR adds a new script that will check that you are logged in before running linter and tests. Sadly this won't verify you have the correct permissions on NPM but it's a start.
> Add helper script to check log in status before going through all publish checks

- README.md
`notion.users.list()` is called without any arguments, but (the TypeScript typings, at least) indicate that it needs to take one argument, so this uses an empty object.
> Fix notion.users.list arg in README.md

- src/api-endpoints.ts
This PR names and exports many more types in `api-endpoints.ts`, focusing on **response** types. Some categories of types that have been exported:
- Top-level objects like page, block, database, and user (in both full and partial forms).
- Rich text objects
- Block types
- User types
- Page property types
(This change stems from a corresponding update to our code generator.)
> Export and name many more response objects

- src/Client.ts
Closes https://github.com/makenotion/notion-sdk-js/issues/329
Previous TypeError:
```
TypeError: Cannot read properties of undefined (reading 'request')
at search (/path/to/node_modules/@notionhq/client/src/Client.ts:511:17)
at iteratePaginatedAPI (/path/to/node_modules/@notionhq/client/src/helpers.ts:50:49)
at iteratePaginatedAPI.next (<anonymous>)
at example.example (/path/to/example.ts)
```
Passing in the `listFn` as `client.search` meant that `this.request({...})` is unavailable unless `search` is an arrow function.
> update search to use arrow function

- src/Client.ts
- src/api-endpoints.ts
This update includes:
- Adding type definitions for `filter_properties` for requests to retrieving a page & querying a database
- Export `BlockObjectRequest` & `BlockObjectRequestWithoutChildren` as types
- Add `this_week` date filter type
- Adds support for constructing a path with an array query param (`express` and other similar libraries use this format)
- Note: Notion's own code generation for types worked successfully for arrays. See `jsonSchemaToTypescriptString`.
> Update type definitions

- .gitignore
- .vscode/settings.json
Seems the `.vscode` directory can be ignored. We already have `.cspell.json` in our project and they support `.cspell.json` as the configuration file in VS Code:
See https://github.com/streetsidesoftware/vscode-spell-checker/blob/add7ae9b37b7d02eadfbd2788ab0b0d6699e09d6/packages/client/src/settings/CSpellSettings.ts#L11-L13.
On the other hand, ignoring the `.vscode` directory can let developers put their editor settings. They can decide to enable or disable specific extension settings for specific projects.
Currently, we don't have other editor settings like `.vscode/launch.json`, `.vscode/tasks.json`, etc. So it's OK to ignore the whole directory.
We could change the rule if we need to put some other project-level configuration files in the `.vscode` directory in the future.
> Ignore VS Code settings directory

- examples/database-email-update/README.md
- examples/notion-github-sync/README.md
Small change: add instruction for giving integration access to database. An error is thrown if this step is not completed first.
Examples that require access to be given where instructions aren't already included: database-email-update, notion-github-sync
> Update example README instructions to include integration access note

- examples/database-email-update/README.md
- examples/database-email-update/example.env
- examples/database-email-update/index.ts
- examples/database-email-update/package.json
- examples/database-email-update/tsconfig.json
- examples/generate-random-data/README.md
- examples/generate-random-data/example.env
- examples/generate-random-data/package.json
- examples/notion-github-sync/package.json
- examples/notion-task-github-pr-sync/package.json
Couple of housekeeping items:
- Update the SDK version in all example projects
- Cleaned up some of the example instructions to keep better consistency and easy of setup
- Migrated email sending example to Typescript 🥳 
- Started migrating templates to a single workspace to make updates easier for the team
- Fixed a bug in the random data example by adding a `rich_text` property to the template database.
- Started adding `example.env` files which users can rename easily to get the expected environment variables.
> SDK Examples housekeeping tasks

- package.json
- src/Client.ts
Problem: `filter_properties` is a query parameter, which gets URI encoded when a request is made with the JS SDK. A bug report came in that when querying for a specific property in the [Query Database endpoint](https://developers.notion.com/reference/post-database-query), an error was occurring stating that the collection schema was invalid.
When you retrieve a database, the response already includes URI-encoded IDs for properties. This problem occurred because our JS SDK was further encoding the ID. For example:
- an ID `U:C<` was returned in the `notion.databases.retrieve()` call as `U%3AC%3C` (in the JS SDK)
- `U%3AC%3C` is passed to `notion.databases.query()` (the JS SDK) which was getting encoded once again to `U%253AC%253C`
- The Notion server looked for `U%253AC%253C` but couldn't …
> Fix bug for encoding filter_properties query parameter.

- .cspell.json
- src/Client.ts
- src/api-endpoints.ts
> Support oauth token endpoint, add wiki verification support, fix issue #420

- src/api-endpoints.ts
Now `createDatabase` and `updateDatabase` allow creating unique ID properties and `getDatabase` will now return unique ID properties.
> Add support for unique ID in database request / responses

- README.md
Updates the example to be typed correctly, specific with isFullPageOrDatabase
> Update readme with isFullPageOrDatabase

- src/helpers.ts
Fixes #468 now that type guard types are wider.
Fixes #448 by adding type guards for `RichTextItemResponse`.
> Allow wider paramter types for type guards and add type guards for `RichTextItemResponse`.

- src/api-endpoints.ts
Update api endpoints with in_trash field in request and response
The goal is to eventually deprecate archived field.
Following guide: https://dev.notion.so/notion/Update-Notion-JS-SDK-57cce3061ed04a33b4663fee8f6f9ad1
verified locally
> update api endpoints with in_trash field in request and response

- src/api-endpoints.ts
This PR updates the SDK `src/api-endpoints.ts` with Notion's latest Public API spec.
Changes:
- Add several missing fields to `LinkMentionResponse`, all of which are optional:
- `title`, `description`, `link_author`, `link_provider`, `thumbnail_url`, `icon_url`, `iframe_url`, `height`, `padding`, `padding_top`
> Add missing optional fields to LinkMentionResponse

- src/Client.ts
- src/api-endpoints.ts
- test/Client.test.ts
Introduce JS SDK methods and data types for the new `oauth/revoke` and `oauth/introspect` endpoints.
We'll include this in an upcoming minor SDK version bump.
> [TASK-239014] Add oauth revoke and introspect endpoints to SDK

- src/api-endpoints.ts
Sync Notion's public API specification as of today (2025-04-08) into `src/api-endpoints.ts`.
**Summary of changes**:
- Refactor common parameter shapes into new types: `InternalFileRequest`, `ExternalFileRequest`, and `InternalOrExternalFileWithNameRequest`
- Support commenting on a non-page block in the Create Comment API by accepting a parent type of `block_id`
> Sync OpenAPI schema as of 2025-04-08 to `src/api-endpoints.ts`

- .github/workflows/ci.yml
- jest.config.js
- package.json
- src/Client.ts
Since `fetch` is stable in the current LTS version of Node, I don't see any good reason for using node-fetch or any other solution than the web standard.
> Use isomorphic fetch

- examples/database-email-update/README.md
This PR updates the path to the correct one. 
There is no file named 'database-update-send-email' in the examples directory.
Changes: 
- Fixed the incorrect example path in [README](https://github.com/makenotion/notion-sdk-js/tree/main/examples/database-email-update)
> docs: fix incorrect example path in README

- examples/intro-to-notion-api/README.md
**nitpick:** incorrect and / or misleading `cd` command
**explanation:** The slash `/` at the beginning of the path points to the root of the filesystem, so `cd /notion-sdk-js` tries to change to a directory that is directly under the root directory. That is not where the cloned repo would be based on the first `git clone` command
**reason for change:** could confuse some beginners 🤷‍♀️
> Update README.md with correct `cd` command

- package.json
Ran `npm version major`
This new version tag will include the following changes: https://github.com/makenotion/notion-sdk-js/compare/650d23bd94c1cd9a4179fcbea25be617e2f5a7e5...d7694613258a01a227ade06a841fcf9207edb801
> Bump major version to 3.0.0

- src/api-endpoints.ts
This PR syncs the latest OpenAPI schema from Notion's public API into `src/api-endpoints.ts`.
These changes include:
* Extracting reusable types for more request & response objects: `ColumnWithChildrenRequest`, `ColumnResponse`, `ColumnBlockWithChildrenRequest`, `ColumnListRequest`
* Adding support for the 🆕 [`width_ratio` parameter and field on `column` type blocks](https://developers.notion.com/reference/block#column-list-and-column)
> Support `width_ratio` parameter and field on `column` Blocks

- examples/intro-to-notion-api/.prettierrc
- examples/intro-to-notion-api/README.md
- examples/intro-to-notion-api/intermediate/5-upload-file.js
- examples/intro-to-notion-api/package.json
- package.json
- src/Client.ts
- src/fetch-types.ts
- test/Client.test.ts
Follow-ups to #565:
- Fix the `FormData` parameter passing logic in `src/Client.ts` for the Send File Upload API
- Add `examples/intro-to-notion-api/intermediate/5-upload-file.js` example of using the File Upload API to upload and attach a file
> Add file upload API example and fix `Blob` send logic

- package.json
This PR commits the result of `npm version minor`, bumping the `package.json` version of `@notionhq/client` from `3.0.1` to `3.1.0`. This includes the following PRs (mostly related to adding basic support for `fileUploads` APIs):
- https://github.com/makenotion/notion-sdk-js/pull/565
- https://github.com/makenotion/notion-sdk-js/pull/566
> Minor version bump: v3.0.1 → v3.1.0

- .nvmrc
- README.md
`nvm use` failed as package is asking for 18 and docs and .nvmrc wanted 12/14 respectively.
> Updates node/nvm version required

- src/api-endpoints.ts
Sync the latest OpenAPI schema for the Notion Public API to `src/api-endpoints.ts`.
Key changes include:
- Add a new field `workspace_limits: { max_file_upload_size_in_bytes: number }` to the `bot` info shape in the User API response.
- Extract the `bot` info object to a reusable type `BotInfoResponse` to reduce the overall file size.
- Use `TextRequest` instead of `StringRequest` for several property response types (e.g. `SelectPropertyResponse `) that now have an increased character limit in the API.
> Add `max_file_upload_size_in_bytes` field to User response

- package.json
- src/Client.ts
- src/fetch-types.ts
#565 and #566 introduced changes to the `SupportedFetch` type that make it incompatible with the browser `fetch` function. Specifically, `SupportedRequestInit['body']` was [changed](https://github.com/makenotion/notion-sdk-js/compare/v3.0.1...v3.1.0#diff-a570c00994d666ae078f11f697662d819f448fd464a194410559e690c374a066L20-R21) to use the `Readable` type from the `node:stream` module, and this is incompatible with the type of `body` in the DOM types library. This causes a type error when trying to pass the browser's `fetch` function for the `fetch` parameter of the `Client` constructor.
A minimal reproduction is available in https://github.com/dvanoni/notion-supportedfetch-types.
This PR changes `SupportedRequestInit['body']` to use the global `FormData` type rather than `Readable`. This …
> fix(types): Support browser fetch and remove node-fetch types

- src/api-endpoints.ts
This PR removes support for the legacy (pre-Q3-2021) shape for page `properties` parameters from `CreatePageBodyParameters` and `UpdatePageBodyParameters` in `src/api-endpoints.ts`.
This collapses the union type of {old properties shape, new properties shape} down to the new shape only.
In the old shape, `properties` was a fairly ambiguous `Record<string, ...>` mapping each property key to the property value (a union type across all possible property types' values) e.g.
```ts
{
// ...
"numberId": 24,
}
```
In the new shape (the only one we want to support going forward), the value must be wrapped in an object that uses the polymorphic `type` pattern with the actual value defined in a sub-object to disambiguate:
```ts
{
// ...
"numberId": {
"type": "number",
"number": 24
}
}
```
This …
> Remove legacy (<=2021) v1 API shape for page properties

- src/api-endpoints.ts
Sync the latest changes to `src/api-endpoints.ts` from Notion's codebase:
- No-op refactors/cleanups: extracting some components into separate type aliases, e.g. `AnnotationRequest`
- Support the new mode in `POST /v1/pages` (`CreatePage`) API where:
- `parent` can be omitted, or passed as `{"workspace": true}`, to create top-level private pages at the workspace level (for public integrations only)
- `properties` is also optional. For standalone pages, this results in title defaulting to an empty string
> CreatePage: support workspace-level private pages (+ misc param type refactors)

- package.json
Commits the result of `npm run major`
This release will include the following changes: https://github.com/makenotion/notion-sdk-js/compare/df95f350ce31c198b74e4d19dcfb02405004ec4f...ksinder-bump-major-version
Considering this "major" only due to https://github.com/makenotion/notion-sdk-js/commit/7f528653d84b6d90ea52357103fc69c628e39bd3 being a removal of deprecated API shape.
> Major version bump: v3.1.3 → v4.0.0

- package.json
- src/Client.ts
- test/Client.test.ts
- Support additional `headers` passed to `notion.request()`
- Bump version to 4.0.1 using `npm version patch`
> Support additional `headers` passed to `notion.request()`

- .github/workflows/ci.yml
- examples/generate-random-data/index.ts
- examples/intro-to-notion-api/intermediate/5-upload-file.ts
- package.json
- src/api-endpoints.ts
Sync Notion's latest public OpenAPI schema for `2025-09-03` to `src/api-endpoints.ts`:
- Add `data_source_id` as a valid type variant for the `DataSourceObjectResponse["parent"]`
- Change valid enum values for `SearchBodyParameters["filter"]["value"]` from `"page" | "database"` to `"page" | "data_source"`
In the latest commit, I also added typechecking of all `examples/` projects as part of CI so we can catch issues more systematically.
> [v5] Sync API shape changes for `data_source` parents and search filter

- src/api-endpoints.ts
This PR syncs the latest changes from Notion's codebase to the TS SDK `src/api-endpoints.ts`. Specifically, the changes here are primarily around preparing for the next release candidate for the v5 version:
- Rename `parent` to `database_parent` on `DataSourceObjectResponse` and introduce a new `parent` field that can be either `database_id` or `data_source_id`  to match `2025-09-03` changes
- Add `data_source_id` to `DatabasePropertyRelationConfigResponseCommon` and only accept `data_source_id` in `RelationPropertyConfigurationRequest` to match `2025-09-03` changes
- Miscellaneous no-op auto-generated docstring/comment additions, e.g. to `SelectColor`
Relying on automated test coverage/successful CI build for these changes ahead of more manual testing ahead of v5 SDK GA.
N/A
> [v5] Data source parent and relation property shape updates

- package-lock.json
- package.json
Following up on https://github.com/makenotion/notion-sdk-js/pull/607, this PR commits the result of `npm version prerelease`, which bumps the package version to `5.0.0-rc.1` ahead of publishing this on NPM.
N/A -- existing CI is sufficient
N/A
> Bump prerelease version: `5.0.0-rc.0` → `5.0.0-rc.1`

- .github/workflows/increment-version.yml
- .github/workflows/publish.yml
**Summary**: 1 logic fix to the NPM publish GitHub Action, and 1 net-new (manual trigger only) Action `increment-version.yml` to bump the patch, minor, major, or premajor version of `@notionhq/client`.
This PR cleans ups an idempotency issue where we have two `npm publish` calls in the `publish.yml` action added in #620, leading to duplicate steps: https://github.com/makenotion/notion-sdk-js/actions/runs/17698864508
<kbd>
</kbd>
The `npm publish` happened correctly, ignoring the pre-publish script (`checkLoggedIn`), but then I had a stray `npm publish` without `--ignore-scripts` afterwards. We need to keep the latter call (since it correctly branches on whether there's a version to upgrade) but add the `--ignore-scripts` flag.
Introduce a new GitHub Action we can use to fully automate the …
> Fix idempotency in NPM publish workflow; add increment-version workflow
